version: "3.9"

services:
  client:
    image: 389798/client-lerna-image
    container_name: vue-3-lerna-container
    build:
      context: ./packages/vue-3-kit
      dockerfile: ./dockerfile
    depends_on:
      - server
    healthcheck:
      test: curl -sS http://127.0.0.1:3000 || echo 1
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    volumes:
      - ./packages/vue-3-kit
    ports:
      - 3000:3000
    networks:
      - lerna-network

  server:
    image: 389798/server-lerna-image
    container_name: express-lerna-container
    build:
      context: ./packages/express-kit
      dockerfile: ./dockerfile
    healthcheck:
      test: curl -sS http://127.0.0.1:5502 || echo 1
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    command: npm run dev
    depends_on:
      - mongodb
    volumes:
      - ./packages/express-kit
    ports:
      - 5500:5500
    networks:
      - lerna-network

  mongodb:
    image: mongo
    container_name: mongo-lerna-container
    ports:
      - 27017:27017
    env_file:
      - ./packages/express-kit/.env
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    networks:
      - lerna-network

volumes:
  mongodb-data:

networks:
  lerna-network:
    driver: bridge
