version: "3.9"

services:
  client:
    image: client-lerna-image
    container_name: vue-3-lerna-container
    depends_on:
      - server
    build:
      context: ./packages/vue-3-kit
      dockerfile: dockerfile
    healthcheck:
      test: curl -sS http://127.0.0.1:3030 || echo 1
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    volumes:
      - ./packages/vue-3-kit
    ports:
      - 3030:3030
    networks:
      - lerna-network

  server:
    image: server-lerna-image
    container_name: express-lerna-container
    depends_on:
      - mongodb
    build:
      context: ./packages/express-kit
      dockerfile: dockerfile
    healthcheck:
      test: curl -sS http://127.0.0.1:5502 || echo 1
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    volumes:
      - ./packages/express-kit
    ports:
      - 5502:5502
    networks:
      - lerna-network

  mongodb:
    image: mongo
    container_name: mongo-lerna-container
    ports:
      - 27017:27017
    env_file:
      - ./packages/express-kit/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    networks:
      - lerna-network

networks:
  lerna-network:
    driver: bridge
